version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "pg_container"
    ports: 
      - "54320:5432"
    volumes:
      - "./db:/docker-entrypoint-initdb.d/"
    restart: always
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=sales
