version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "pg_container"
    ports: 
      - "54320:5432"
    volumes:
      - ./Docker:/docker-entrypoint-initdb.d/
volumes:
  my_dbdata:
